### PR TITLE
reverse order of cmds and subs evaluation

### PR DESCRIPTION
**Pull request by et1975**
Fix for [browser/#66](https://github.com/elmish/browser/issues/66)

### CODE REVIEW

**Comment by kspeakman** [comment]
I think this change makes sense. In effect, it sets up subscriptions before the user init instead of after.

Be aware that this is potentially a breaking change. If the user currently depends on msgs emitted from `init` Cmds to occur before msgs from subscriptions. A specific scenario doesn't come to mind. But I also didn't think of using `newUrl` from top level `init`.

**Review by kspeakman — COMMENTED** [review]
Left comment in issue.

**Comment by MangelMaxime** [comment]
On my side, the question I have is do we need reverse the order only when initialising the program or also in the inner loop (like done in this PR) ?

I don't have a scenario in mind for that, but I because I can't shake off the question of my head I preferred to asked it out loud 😅

**Comment by kspeakman** [comment]
I think consistency is best. And in general, this is exactly the kind of scenario I had in mind. Subscriptions setup services used by the page.

The only lingering doubt I have is: what if I want to run something before subscriptions? I guess the answer there is to run it before running the program or as the first subscription.

**Comment by kspeakman** [comment]
Forgot the obvious: running something before subscriptions is already in the page's control. It can not return any subscriptions, run whatever initialization it wants, then return them.

**Pull request merged**
