### PR TITLE
Elmish for WebSharper apps

### PR DESCRIPTION
**Pull request by granicz**
Added #263

### CODE REVIEW

**Review by et1975 — APPROVED** [review]

**Comment by kspeakman** [comment]
@granicz I'm embarrassed to say I'm a bit lost on this feature. My understanding certainly isn't required to proceed. But if you get a moment, can you explain the context around this?

**Comment by granicz** [comment]
Sure, let me take a bird's eye view to illustrate. While Elmish is built on .NET, it is a particularly useful abstraction to structure UI applications of all sorts (desktop, mobile, web, etc.). It by design does not involve or care about any given view, but you can build further logic around it to target different "UI platforms" such as WPF, JavaScript/DOM, Xamarin, etc. - and instantiate Elmish's abstract notion of a "view" with something concrete in those.

Now, applications that end up running outside of .NET (say, in JavaScript) need the Elmish codebase processed/transpiled/translated to their own target language/representation. Transpiling often reinterprets the underlying code with additional or different semantics, either via compiler directives you see for Fable (`#if FABLE_COMPILER ... #else ...`), or via other metaprogramming techniques (such as code attributes, shadowing of identifiers, or full-blown proxies such as in WebSharper). For this reason, one could argue they should be placed in the source repository - which is a matter of taste and/or necessity of the underlying toolset.

This repository has always provided the translation to JavaScript with Fable, allowing Fable apps to use and build on Elmish, but not with WebSharper, which is the hole I am filling with the above PR. Once merged, it will enable WebSharper apps to use and build on Elmish in the same way as well.

Hope this helps. Let me know if you need further clarification, happy to elaborate further.

**Comment by et1975** [comment]
Had to flatten it a bit as nuget props wheren't happy with the relative paths.

**Comment by kspeakman** [comment]
@granicz Thanks for the explanation. Makes sense. I just wasn't aware of WebSharper's mechanism of usage. The code added for WebSharper.Elmish is amazingly small, so it didn't give me any hints. :)

**Pull request merged**
