### PR TITLE
Add debugger support

### PR DESCRIPTION
**Pull request by MangelMaxime**

### CODE REVIEW

**Comment by forki** [comment]
this is cool! we just need a bit in the readme on how to get it started, what do I need to install. what dou I have to press? things like that

**Comment by et1975** [comment]
I'd rather keep the counter simple. The reason being, if you don't know you need to have the extension installed you're going to see nothing but errors in the console log. Could be unpleasant first experience.

**Comment by forki** [comment]
yeah just noticed that. throws errors all over the place. 

So better idea:

* use one of the other samples. 
* make it super clear what I have to install

**Comment by MangelMaxime** [comment]
Agree with @et1975 
Was doing it for @forki

Perhaps we can simply wait the doc site (promise I working on it) and we will be able from here to provide all the info needed to the users.
We will be able to explain how to use the template, debugger, elmish structure, etc. :)

**Comment by forki** [comment]
I'm doing a talk on Tuesday and want to show that this model allows time traveling. 
Talk is about fable |> RN but I have an elmish block where I want to talk about such things
Any recommendations how to go forward?

**Comment by et1975** [comment]
Elmish 0.8 branch works for RN (with debugger), so I'd do that and say that support for Fable 1.x is in the works.

**Comment by forki** [comment]
Elmish blog is fully in react proper. I just need a sample and some
installation instructions.

Am 13.04.2017 2:30 nachm. schrieb "Eugene Tolmachev" <
notifications@github.com>:

Elmish 0.8 branch works for RN (with debugger), so I'd do that and say that
support for Fable 1.x is in the works.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/fable-compiler/fable-elmish/pull/74#issuecomment-293881946>,
or mute the thread

**Comment by forki** [comment]
elmish block - not blog

**Comment by MangelMaxime** [comment]
I am closing this PR to avoid error :)

**Pull request closed without merging**
